name: Wasm build
description:
  Build the workspace for the `wasm32-unknown-unknown` target. Assumes the
  repo is already checked out and a Rust toolchain with caching is already
  set up, e.g. via `actions-rust-lang/setup-rust-toolchain`.

inputs:
  packages:
    description: List of prerequisite Ubuntu packages, separated by whitespace
    required: false
    default: ''
runs:
  using: composite
  steps:
    - uses: $/.github/actions/install-deps
      if: inputs.packages != ''
      with:
        packages: "${{ inputs.packages }}"
    - shell: bash
      run: rustup target add wasm32-unknown-unknown
    - name: Wasm build
      shell: bash
      run: cargo build --target wasm32-unknown-unknown
