name: Generate and deploy crate docs

on:
  workflow_call:

permissions: {}

jobs:
  docs:
    name: Generate crate documentation
    runs-on: ubuntu-latest
    # `contents: write` for the `gh-pages` deploy
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Generate documentation
        env:
          RUSTDOCFLAGS: "--enable-index-page -Zunstable-options"
          RUSTC_BOOTSTRAP: 1
        run: |
          cargo doc --workspace --no-deps
      - name: Deploy documentation
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./target/doc
          destination_dir: docs
