# Uses deny.toml if found
name: cargo-deny

on:
  workflow_call:

permissions: {}

jobs:
  cargo-deny:
    permissions:
      contents: read
    name: cargo-deny (advisories, licenses, bans, ...)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: EmbarkStudios/cargo-deny-action@v2
